// Table STATIQUE et EXHAUSTIVE des 325 villes/lieux éditoriaux (FR -> nom de
// requête Unsplash en anglais), générée le 2026-07-23 à partir de
// scripts/verify-city-name-translations-cache.json (audit croisé Wikipédia
// des 325 villes, fait ville par ville, voir scripts/translate-city-names.mjs
// + scripts/verify-city-name-translations.mjs) et de corrections manuelles
// supplémentaires (sites/paysages non confirmables par le géocodeur, ou
// confirmés mais avec la mauvaise entité administrative — ex: Londres
// géocode en "Greater London", Huacachina en "Ica" la ville voisine).
//
// Remplace intégralement la résolution EN DIRECT par géocodeur + Google
// Translate pour toute ville de cette liste : plus aucun appel réseau
// nécessaire, donc plus aucune fenêtre d'échec transitoire possible pour ces
// 325 villes. Un géocodage/traduction en direct ne reste utilisé (voir
// resolveEnglishCityNameForQuery, api/_lib/cityImages.js) QUE pour une ville
// ajoutée à la main par un utilisateur, absente de cette liste.
//
// Clé = `${country_code}:${city_name normalisé (trim + minuscules)}`.
export const CITY_NAME_QUERY_OVERRIDES = {
  "ARE:abu dhabi": "Abu Dhabi",
  "ARE:dubaï": "Dubai",
  "AUS:adélaïde": "Adelaide",
  "AUS:blue mountains": "Blue Mountains",
  "AUS:brisbane": "Brisbane",
  "AUS:cairns": "Cairns",
  "AUS:great ocean road": "Great Ocean Road",
  "AUS:melbourne": "Melbourne",
  "AUS:perth": "Perth",
  "AUS:rottnest island": "Rottnest Island",
  "AUS:sydney": "Sydney",
  "AUS:uluru": "Uluru",
  "AUT:graz": "Graz",
  "AUT:hallstatt": "Hallstatt",
  "AUT:innsbruck": "Innsbruck",
  "AUT:salzbourg": "Salzburg",
  "AUT:vienne": "Vienna",
  "BEL:anvers": "Antwerp",
  "BEL:bruges": "Bruges",
  "BEL:bruxelles": "Brussels",
  "BEL:gand": "Ghent",
  "BEL:liège": "Liège",
  "BRA:brasília": "Brasília",
  "BRA:foz do iguaçu": "Foz do Iguaçu",
  "BRA:manaus": "Manaus",
  "BRA:pantanal": "Pantanal",
  "BRA:paraty": "Paraty",
  "BRA:rio de janeiro": "Rio de Janeiro",
  "BRA:salvador": "Salvador",
  "BRA:são paulo": "São Paulo",
  "CAN:banff": "Banff",
  "CAN:chute montmorency": "Montmorency Falls",
  "CAN:chutes du niagara": "Niagara Falls",
  "CAN:halifax": "Halifax",
  "CAN:jasper": "Jasper",
  "CAN:kamloops": "Kamloops",
  "CAN:lake louise": "Lake Louise",
  "CAN:montréal": "Montreal",
  "CAN:niagara falls": "Niagara Falls",
  "CAN:ottawa": "Ottawa",
  "CAN:québec": "Quebec",
  "CAN:toronto": "Toronto",
  "CAN:vancouver": "Vancouver",
  "CAN:victoria": "Victoria",
  "CAN:whistler": "Whistler",
  "CHE:berne": "Bern",
  "CHE:genève": "Geneva",
  "CHE:interlaken": "Interlaken",
  "CHE:jungfraujoch": "Jungfraujoch",
  "CHE:lucerne": "Lucerne",
  "CHE:montreux": "Montreux",
  "CHE:zermatt": "Zermatt",
  "CHE:zurich": "Zurich",
  "CHN:canton": "Canton",
  "CHN:chengdu": "Chengdu",
  "CHN:dali": "Dali",
  "CHN:grande muraille": "Great Wall",
  "CHN:guilin": "Guilin",
  "CHN:hangzhou": "Hangzhou",
  "CHN:hong kong": "Hong Kong",
  "CHN:kunming": "Kunming",
  "CHN:lijiang": "Lijiang",
  "CHN:mutianyu": "Mutianyu",
  "CHN:pékin": "Beijing",
  "CHN:shanghai": "Shanghai",
  "CHN:suzhou": "Suzhou",
  "CHN:xi'an": "Xi'an",
  "CZE:brno": "Brno",
  "CZE:kutná hora": "Kutná Hora",
  "CZE:prague": "Prague",
  "CZE:český krumlov": "Český Krumlov",
  "DEU:berlin": "Berlin",
  "DEU:cologne": "Cologne",
  "DEU:dresde": "Dresden",
  "DEU:francfort": "Frankfurt",
  "DEU:hambourg": "Hamburg",
  "DEU:munich": "Munich",
  "DEU:neuschwanstein": "Neuschwanstein",
  "DEU:potsdam": "Potsdam",
  "DEU:rüdesheim": "Rüdesheim",
  "EGY:alexandrie": "Alexandria",
  "EGY:assouan": "Aswan",
  "EGY:edfou": "Edfu",
  "EGY:gizeh": "Giza",
  "EGY:hurghada": "Hurghada",
  "EGY:le caire": "Cairo",
  "EGY:louxor": "Luxor",
  "ESP:barcelone": "Barcelona",
  "ESP:bilbao": "Bilbao",
  "ESP:cordoue": "Cordoba",
  "ESP:grenade": "Granada",
  "ESP:madrid": "Madrid",
  "ESP:malaga": "Malaga",
  "ESP:montserrat": "Montserrat",
  "ESP:saint-sébastien": "San Sebastian",
  "ESP:ségovie": "Segovia",
  "ESP:séville": "Seville",
  "ESP:tolède": "Toledo",
  "ESP:valence": "Valencia",
  "FRA:aix-en-provence": "Aix-en-Provence",
  "FRA:arles": "Arles",
  "FRA:avignon": "Avignon",
  "FRA:biarritz": "Biarritz",
  "FRA:bordeaux": "Bordeaux",
  "FRA:carcassonne": "Carcassonne",
  "FRA:cassis": "Cassis",
  "FRA:colmar": "Colmar",
  "FRA:lyon": "Lyon",
  "FRA:marseille": "Marseille",
  "FRA:monaco": "Monaco",
  "FRA:montpellier": "Montpellier",
  "FRA:nice": "Nice",
  "FRA:paris": "Paris",
  "FRA:saint-jean-de-luz": "Saint-Jean-de-Luz",
  "FRA:saint-émilion": "Saint-Émilion",
  "FRA:strasbourg": "Strasbourg",
  "FRA:sète": "Sète",
  "FRA:toulouse": "Toulouse",
  "FRA:tours": "Tours",
  "FRA:versailles": "Versailles",
  "GBR:cardiff": "Cardiff",
  "GBR:glasgow": "Glasgow",
  "GBR:liverpool": "Liverpool",
  "GBR:loch ness": "Loch Ness",
  "GBR:londres": "London",
  "GBR:manchester": "Manchester",
  "GBR:oxford": "Oxford",
  "GBR:york": "York",
  "GBR:édimbourg": "Edinburgh",
  "GRC:athènes": "Athens",
  "GRC:cap sounion": "Cape Sounion",
  "GRC:délos": "Delos",
  "GRC:la canée": "Chania",
  "GRC:mykonos": "Mykonos",
  "GRC:rhodes": "Rhodes",
  "GRC:santorin": "Santorini",
  "GRC:thessalonique": "Thessaloniki",
  "HRV:dubrovnik": "Dubrovnik",
  "HRV:hvar": "Hvar",
  "HRV:lokrum": "Lokrum",
  "HRV:plitvice": "Plitvice",
  "HRV:rovinj": "Rovinj",
  "HRV:split": "Split",
  "HRV:trogir": "Trogir",
  "HRV:zadar": "Zadar",
  "HRV:zagreb": "Zagreb",
  "HUN:budapest": "Budapest",
  "IDN:gili trawangan": "Gili Trawangan",
  "IDN:jakarta": "Jakarta",
  "IDN:labuan bajo": "Labuan Bajo",
  "IDN:nusa penida": "Nusa Penida",
  "IDN:seminyak": "Seminyak",
  "IDN:ubud": "Ubud",
  "IDN:yogyakarta": "Yogyakarta",
  "IND:agra": "Agra",
  "IND:delhi": "Delhi",
  "IND:jaipur": "Jaipur",
  "IND:jodhpur": "Jodhpur",
  "IND:kochi": "Kochi",
  "IND:mumbai": "Mumbai",
  "IND:udaipur": "Udaipur",
  "IND:varanasi": "Varanasi",
  "IRL:cork": "Cork",
  "IRL:dublin": "Dublin",
  "IRL:falaises de moher": "Cliffs of Moher",
  "IRL:galway": "Galway",
  "IRL:howth": "Howth",
  "IRL:killarney": "Killarney",
  "ITA:agrigente": "Agrigento",
  "ITA:bologne": "Bologna",
  "ITA:florence": "Florence",
  "ITA:milan": "Milan",
  "ITA:naples": "Naples",
  "ITA:palerme": "Palermo",
  "ITA:pise": "Pisa",
  "ITA:pompéi": "Pompeii",
  "ITA:rome": "Rome",
  "ITA:tivoli": "Tivoli",
  "ITA:turin": "Turin",
  "ITA:venise": "Venice",
  "JPN:fukuoka": "Fukuoka",
  "JPN:hiroshima": "Hiroshima",
  "JPN:kamakura": "Kamakura",
  "JPN:kanazawa": "Kanazawa",
  "JPN:kyoto": "Kyoto",
  "JPN:miyajima": "Miyajima",
  "JPN:nagasaki": "Nagasaki",
  "JPN:nara": "Nara",
  "JPN:osaka": "Osaka",
  "JPN:sapporo": "Sapporo",
  "JPN:tokyo": "Tokyo",
  "KOR:busan": "Busan",
  "KOR:dmz": "DMZ",
  "KOR:gyeongju": "Gyeongju",
  "KOR:jeju": "Jeju",
  "KOR:séoul": "Seoul",
  "MAR:agadir": "Agadir",
  "MAR:casablanca": "Casablanca",
  "MAR:chefchaouen": "Chefchaouen",
  "MAR:essaouira": "Essaouira",
  "MAR:fès": "Fez",
  "MAR:marrakech": "Marrakesh",
  "MAR:merzouga": "Merzouga",
  "MAR:ouarzazate": "Ouarzazate",
  "MAR:rabat": "Rabat",
  "MAR:tanger": "Tangier",
  "MEX:bacalar": "Bacalar",
  "MEX:cancún": "Cancun",
  "MEX:chichén itzá": "Chichen Itza",
  "MEX:guadalajara": "Guadalajara",
  "MEX:guanajuato": "Guanajuato",
  "MEX:isla mujeres": "Isla Mujeres",
  "MEX:mexico": "Mexico",
  "MEX:monte albán": "Monte Albán",
  "MEX:mérida": "Merida",
  "MEX:oaxaca": "Oaxaca",
  "MEX:puerto vallarta": "Puerto Vallarta",
  "MEX:sian ka'an": "Sian Ka'an",
  "MEX:teotihuacán": "Teotihuacan",
  "MEX:tulum": "Tulum",
  "MEX:uxmal": "Uxmal",
  "MEX:valladolid": "Valladolid",
  "MYS:george town": "George Town",
  "MYS:grottes de batu": "Batu Caves",
  "MYS:kota kinabalu": "Kota Kinabalu",
  "MYS:kuala lumpur": "Kuala Lumpur",
  "MYS:langkawi": "Langkawi",
  "MYS:malacca": "Malacca",
  "NLD:amsterdam": "Amsterdam",
  "NLD:la haye": "The Hague",
  "NLD:rotterdam": "Rotterdam",
  "NLD:utrecht": "Utrecht",
  "NLD:zaanse schans": "Zaanse Schans",
  "PER:arequipa": "Arequipa",
  "PER:canyon de colca": "Colca Canyon",
  "PER:cusco": "Cusco",
  "PER:huacachina": "Huacachina",
  "PER:lima": "Lima",
  "PER:machu picchu": "Machu Picchu",
  "PER:maras et moray": "Maras and Moray",
  "PER:paracas": "Paracas",
  "PER:puerto maldonado": "Puerto Maldonado",
  "PER:puno": "Puno",
  "PER:vallée sacrée": "Sacred Valley",
  "PER:vinicunca": "Vinicunca",
  "PHL:bohol": "Bohol",
  "PHL:boracay": "Boracay",
  "PHL:cebu": "Cebu",
  "PHL:coron": "Coron",
  "PHL:el nido": "El Nido",
  "PHL:manille": "Manila",
  "PHL:siargao": "Siargao",
  "POL:auschwitz": "Auschwitz",
  "POL:cracovie": "Krakow",
  "POL:gdańsk": "Gdańsk",
  "POL:oświęcim": "Oświęcim",
  "POL:varsovie": "Warsaw",
  "POL:wieliczka": "Wieliczka",
  "POL:wrocław": "Wrocław",
  "PRT:coimbra": "Coimbra",
  "PRT:funchal": "Funchal",
  "PRT:lagos": "Lagos",
  "PRT:lisbonne": "Lisbon",
  "PRT:porto": "Porto",
  "PRT:sintra": "Sintra",
  "SGP:singapour": "Singapore",
  "THA:ayutthaya": "Ayutthaya",
  "THA:baie de phang nga": "Phang Nga Bay",
  "THA:bangkok": "Bangkok",
  "THA:chiang mai": "Chiang Mai",
  "THA:chiang rai": "Chiang Rai",
  "THA:damnoen saduak": "Damnoen Saduak",
  "THA:ko phi phi": "Ko Phi Phi",
  "THA:koh samui": "Koh Samui",
  "THA:krabi": "Krabi",
  "THA:phuket": "Phuket",
  "THA:sukhothai": "Sukhothai",
  "TUR:antalya": "Antalya",
  "TUR:büyükada": "Büyükada",
  "TUR:göreme": "Göreme",
  "TUR:istanbul": "Istanbul",
  "TUR:izmir": "Izmir",
  "TUR:pamukkale": "Pamukkale",
  "TUR:éphèse": "Ephesus",
  "TWN:hualien": "Hualien",
  "TWN:jiufen": "Jiufen",
  "TWN:kaohsiung": "Kaohsiung",
  "TWN:sun moon lake": "Sun Moon Lake",
  "TWN:taichung": "Taichung",
  "TWN:tainan": "Tainan",
  "TWN:taipei": "Taipei",
  "USA:boston": "Boston",
  "USA:chicago": "Chicago",
  "USA:death valley": "Death Valley",
  "USA:everglades": "Everglades",
  "USA:grand canyon": "Grand Canyon",
  "USA:grand canyon village": "Grand Canyon Village",
  "USA:honolulu": "Honolulu",
  "USA:key west": "Key West",
  "USA:la nouvelle-orléans": "New Orleans",
  "USA:las vegas": "Las Vegas",
  "USA:los angeles": "Los Angeles",
  "USA:miami": "Miami",
  "USA:new york": "New York",
  "USA:orlando": "Orlando",
  "USA:philadelphie": "Philadelphia",
  "USA:san diego": "San Diego",
  "USA:san francisco": "San Francisco",
  "USA:sausalito": "Sausalito",
  "USA:seattle": "Seattle",
  "USA:springdale": "Springdale",
  "USA:washington": "Washington",
  "USA:yosemite valley": "Yosemite Valley",
  "VNM:baie d'halong": "Halong Bay",
  "VNM:cu chi": "Cu Chi",
  "VNM:da nang": "Da Nang",
  "VNM:hanoï": "Hanoi",
  "VNM:ho chi minh-ville": "Ho Chi Minh City",
  "VNM:hoi an": "Hoi An",
  "VNM:hué": "Hue",
  "VNM:my son": "My Son",
  "VNM:my tho": "My Tho",
  "VNM:ninh binh": "Ninh Binh",
  "VNM:phú quốc": "Phú Quốc",
  "VNM:sapa": "Sapa",
};

export function cityNameQueryOverride(cityName, countryCode) {
  const key = `${countryCode}:${cityName.trim().toLowerCase()}`;
  return CITY_NAME_QUERY_OVERRIDES[key] || null;
}
